# Generated by Django 5.2.7 on 2025-11-13 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("libraries", "0035_releasereport"),
        ("versions", "0025_version_versions_ve_active_ae486b_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunitySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="Start date of the summary period"),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="End date of the summary period"),
                ),
                ("summary_data", models.JSONField(help_text="Summary data by topic")),
                ("topics_count", models.IntegerField(default=0)),
                ("recent_emails_count", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this summary is currently active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Community Summary",
                "verbose_name_plural": "Community Summaries",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["-generated_at", "is_active"],
                        name="rag_service_generat_3144df_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LibraryFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_faqs",
                        to="libraries.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Library FAQ",
                "verbose_name_plural": "Library FAQs",
                "ordering": ["library", "question"],
                "indexes": [
                    models.Index(
                        fields=["library", "is_active"],
                        name="rag_service_library_bf4977_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LibrarySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary_text",
                    models.TextField(help_text="AI-generated summary of the library"),
                ),
                (
                    "key_features",
                    models.JSONField(default=list, help_text="List of key features"),
                ),
                (
                    "use_cases",
                    models.JSONField(default=list, help_text="List of use cases"),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_summaries",
                        to="libraries.library",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_rag_summaries",
                        to="versions.version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Library Summary",
                "verbose_name_plural": "Library Summaries",
                "ordering": ["-generated_at"],
                "unique_together": {("library", "version")},
            },
        ),
    ]
