# Generated by Django 5.2.7 on 2025-11-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rag_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="communitysummary",
            name="need_review",
            field=models.BooleanField(
                default=True,
                help_text="Whether this summary needs review before being displayed",
            ),
        ),
        migrations.AddIndex(
            model_name="communitysummary",
            index=models.Index(
                fields=["-generated_at", "need_review"],
                name="rag_service_generat_50c53e_idx",
            ),
        ),
    ]
